apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: [[ forms[0].name ]]
[[ forms[0].namespace ? "  namespace: "+forms[0].namespace + "\n" : ""]]

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: [[ forms[0].name ]]
            image: busybox
            command:
            - ""

