apiVersion: v1
kind: Service
metadata:
  name: [[ forms[0].name ]]
[[ forms[0].namespace ? "  namespace: "+forms[0].namespace + "\n" : ""]]

spec:
  type: [[ forms[0].type ]]
  ports:
    - port: [[ forms[0].port ]]
      targetPort: [[ forms[0].targetPort ]]
  selector:
    [[ forms[0].podSelector ]]